Class {
	#name : 'ErrorNativeOpenCLRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-OpenCL-Private-Errors-Core',
	#package : 'Rudesheim-OpenCL-Private',
	#tag : 'Errors-Core'
}

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> BufferCreationFailed [

	^ BufferCreationFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> CommandQueueCreationFailed [

	^ CommandQueueCreationFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> CommandQueueFinishFailed [

	^ CommandQueueFinishFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> CommandQueueFlushFailed [

	^ CommandQueueFlushFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> ContextCreationFailed [

	^ ContextCreationFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> DeviceEnumerationFailed [

	^ DeviceEnumerationFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> EnqueueCopyFailed [

	^ EnqueueCopyFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> EnqueueFillFailed [

	^ EnqueueFillFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> EnqueueKernelFailed [

	^ EnqueueKernelFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> EnqueueMapFailed [

	^ EnqueueMapFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> EnqueueUnmapFailed [

	^ EnqueueUnmapFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> EventCreationFailed [

	^ EventCreationFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> EventStatusChangeFailed [

	^ EventStatusChangeFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> EventWaitFailed [

	^ EventWaitFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> KernelCreationFailed [

	^ KernelCreationFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> NotSupported [ ^ NotSupportedOpenCLRudesheim
]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> PlatformEnumerationFailed [

	^ PlatformEnumerationFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> Primitive [

	^ PrimitiveErrorNativeOpenCLRudesheim.
]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> ProgramBuildFailed [

	^ ProgramBuildFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> ProgramCompileFailed [
	^ ProgramCompileFailedOpenCLRudesheim.
]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> ProgramCompileNotSupported [
	^ ProgramCompileNotSupportedOpenCLRudesheim.
]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> ProgramCreationFailed [

	^ ProgramCreationFailedOpenCLRudesheim.

]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> ProgramLinkFailed [
	^ ProgramLinkFailedOpenCLRudesheim.
]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> ProgramLinkNotSupported [
	^ ProgramLinkNotSupportedOpenCLRudesheim.
]

{ #category : 'namespace' }
ErrorNativeOpenCLRudesheim class >> SetKernelArgumentFailed [

	^ SetKernelArgumentFailedOpenCLRudesheim.

]
