Class {
	#name : 'HostPtrOpenCLRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-OpenCL-Private-Namespace',
	#package : 'Rudesheim-OpenCL-Private',
	#tag : 'Namespace'
}

{ #category : 'namespace' }
HostPtrOpenCLRudesheim class >> Alloc [

	^ AllocHostPtrOpenCLRudesheim.
]

{ #category : 'namespace' }
HostPtrOpenCLRudesheim class >> Copy [

	^ CopyHostPtrOpenCLRudesheim.
]

{ #category : 'namespace' }
HostPtrOpenCLRudesheim class >> Use [

	^ UseHostPtrOpenCLRudesheim.
]
