Class {
	#name : 'NativeOpenCLRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-OpenCL-Private-Namespace',
	#package : 'Rudesheim-OpenCL-Private',
	#tag : 'Namespace'
}

{ #category : 'namespace' }
NativeOpenCLRudesheim class >> Error [

	^ ErrorNativeOpenCLRudesheim.
]

{ #category : 'namespace' }
NativeOpenCLRudesheim class >> Functions [

	^ FunctionsNativeOpenCLRudesheim.
]

{ #category : 'namespace' }
NativeOpenCLRudesheim class >> Handle [ ^ HandleNativeOpenCLRudesheim
]

{ #category : 'namespace' }
NativeOpenCLRudesheim class >> ID [ ^ IDNativeOpenCLRudesheim
]

{ #category : 'namespace' }
NativeOpenCLRudesheim class >> Library [

	^ LibraryNativeOpenCLRudesheim.
]
