Class {
	#name : 'OpenCLRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-OpenCL-Namespace',
	#package : 'Rudesheim-OpenCL',
	#tag : 'Namespace'
}

{ #category : 'namespace' }
OpenCLRudesheim class >> Accelerator [

	^ AcceleratorOpenCLRudesheim.
]

{ #category : 'namespace' }
OpenCLRudesheim class >> All [

	^ AllOpenCLRudesheim
]

{ #category : 'namespace' }
OpenCLRudesheim class >> Buffer [

	^ BufferOpenCLRudesheim.
]

{ #category : 'namespace' }
OpenCLRudesheim class >> BuildLog [
	^ BuildLogOpenCLRudesheim.
]

{ #category : 'namespace' }
OpenCLRudesheim class >> CommandQueue [

	^ CommandQueueOpenCLRudesheim.
]

{ #category : 'namespace' }
OpenCLRudesheim class >> Context [

	^ ContextOpenCLRudesheim.
]

{ #category : 'namespace' }
OpenCLRudesheim class >> Cpu [

	^ CpuOpenCLRudesheim
]

{ #category : 'namespace' }
OpenCLRudesheim class >> Custom [

	^ CustomOpenCLRudesheim
]

{ #category : 'namespace' }
OpenCLRudesheim class >> Default [

	^ DefaultOpenCLRudesheim
]

{ #category : 'namespace' }
OpenCLRudesheim class >> Device [

	^ DeviceOpenCLRudesheim
]

{ #category : 'namespace' }
OpenCLRudesheim class >> ElementType [

	^ ElementTypeOpenCLRudesheim
]

{ #category : 'namespace' }
OpenCLRudesheim class >> Event [

	^ EventOpenCLRudesheim.
]

{ #category : 'namespace' }
OpenCLRudesheim class >> Gpu [

	^ GpuOpenCLRudesheim
]

{ #category : 'namespace' }
OpenCLRudesheim class >> HostPtr [

	^ HostPtrOpenCLRudesheim.
]

{ #category : 'namespace' }
OpenCLRudesheim class >> Kernel [

	^ KernelOpenCLRudesheim.
]

{ #category : 'namespace' }
OpenCLRudesheim class >> Native [

	^ NativeOpenCLRudesheim.
]

{ #category : 'namespace' }
OpenCLRudesheim class >> OS [
	^ OSOpenCLRudesheim.
]

{ #category : 'namespace' }
OpenCLRudesheim class >> Platform [

	^ PlatformOpenCLRudesheim
]

{ #category : 'namespace' }
OpenCLRudesheim class >> Program [

	^ ProgramOpenCLRudesheim.
]

{ #category : 'namespace' }
OpenCLRudesheim class >> ReadOnly [

	^ ReadOnlyOpenCLRudesheim.
]

{ #category : 'namespace' }
OpenCLRudesheim class >> ReadWrite [

	^ ReadWriteOpenCLRudesheim
]

{ #category : 'namespace' }
OpenCLRudesheim class >> WriteOnly [

	^ WriteOnlyOpenCLRudesheim.
]
